apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: auth-service:latest
          ports:
            - containerPort: 5001
          env:
            - name: MONGO_URI
              value: "mongodb+srv://medicare_user:iHateMern99@cluster0.ilgjnhv.mongodb.net/medicare_auth?retryWrites=true&w=majority&appName=Cluster0"
            - name: JWT_SECRET
              value: "super_secret_key_123"
            - name: PORT
              value: "5001"